version: "3.7"

services:
  web:
    build:
      context: ./public-html
      dockerfile: Dockerfile
    container_name: first-docker
    #image: mkphp/php-ibm-odbc:apache
    image: php:7.3-apache
    ports:
      - 8082:80
    volumes:
      -  ./public-html:/var/www/html/
      #- ./db2consv_ee.lic:/opt/ibm/dsdriver/clidriver/license/db2consv_ee.lic
      #- ./000-default.conf:/etc/apache2/sites-available/000-default.conf
    #env_file:
      #- ./.env
    #extra_hosts:
    #  - "otherhost:10.11.12.13" 
    #privileged: true
    #db:
      #container_name: mongo-db
      #image: mongo
